/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class to_augmented_reality_android_em_recorder_NativeFrameBuffer */

#ifndef _Included_to_augmented_reality_android_em_recorder_NativeFrameBuffer
#define _Included_to_augmented_reality_android_em_recorder_NativeFrameBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     to_augmented_reality_android_em_recorder_NativeFrameBuffer
 * Method:    construct
 * Signature: (IILjava/lang/String;Z)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_to_augmented_reality_android_em_recorder_NativeFrameBuffer_construct
  (JNIEnv *, jclass, jint, jint, jstring, jboolean);

/*
 * Class:     to_augmented_reality_android_em_recorder_NativeFrameBuffer
 * Method:    destroy
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_recorder_NativeFrameBuffer_destroy
  (JNIEnv *, jclass, jobject);

/*
 * Class:     to_augmented_reality_android_em_recorder_NativeFrameBuffer
 * Method:    bufferOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_recorder_NativeFrameBuffer_bufferOn
  (JNIEnv *, jobject);

/*
 * Class:     to_augmented_reality_android_em_recorder_NativeFrameBuffer
 * Method:    bufferOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_recorder_NativeFrameBuffer_bufferOff
  (JNIEnv *, jobject);

/*
 * Class:     to_augmented_reality_android_em_recorder_NativeFrameBuffer
 * Method:    bufferClear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_recorder_NativeFrameBuffer_bufferClear
  (JNIEnv *, jobject);

/*
 * Class:     to_augmented_reality_android_em_recorder_NativeFrameBuffer
 * Method:    bufferEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_recorder_NativeFrameBuffer_bufferEmpty
  (JNIEnv *, jobject);

/*
 * Class:     to_augmented_reality_android_em_recorder_NativeFrameBuffer
 * Method:    startTimestamp
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_recorder_NativeFrameBuffer_startTimestamp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     to_augmented_reality_android_em_recorder_NativeFrameBuffer
 * Method:    push
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_recorder_NativeFrameBuffer_push
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     to_augmented_reality_android_em_recorder_NativeFrameBuffer
 * Method:    pushYUV
 * Signature: (JLjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;III)V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_recorder_NativeFrameBuffer_pushYUV
  (JNIEnv *, jobject, jlong, jobject, jint, jobject, jint, jint, jobject, jint, jint, jint);

/*
 * Class:     to_augmented_reality_android_em_recorder_NativeFrameBuffer
 * Method:    writeOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_recorder_NativeFrameBuffer_writeOn
  (JNIEnv *, jobject);

/*
 * Class:     to_augmented_reality_android_em_recorder_NativeFrameBuffer
 * Method:    writeOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_recorder_NativeFrameBuffer_writeOff
  (JNIEnv *, jobject);

/*
 * Class:     to_augmented_reality_android_em_recorder_NativeFrameBuffer
 * Method:    writeCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_to_augmented_reality_android_em_recorder_NativeFrameBuffer_writeCount
  (JNIEnv *, jobject);

/*
 * Class:     to_augmented_reality_android_em_recorder_NativeFrameBuffer
 * Method:    writeFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_recorder_NativeFrameBuffer_writeFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     to_augmented_reality_android_em_recorder_NativeFrameBuffer
 * Method:    closeFile
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_recorder_NativeFrameBuffer_closeFile
  (JNIEnv *, jobject);

/*
 * Class:     to_augmented_reality_android_em_recorder_NativeFrameBuffer
 * Method:    flushFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_recorder_NativeFrameBuffer_flushFile
  (JNIEnv *, jobject);

/*
 * Class:     to_augmented_reality_android_em_recorder_NativeFrameBuffer
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_recorder_NativeFrameBuffer_stop
  (JNIEnv *, jobject);

/*
 * Class:     to_augmented_reality_android_em_recorder_NativeFrameBuffer
 * Method:    openRead
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_recorder_NativeFrameBuffer_openRead
  (JNIEnv *, jobject, jstring);

/*
 * Class:     to_augmented_reality_android_em_recorder_NativeFrameBuffer
 * Method:    read
 * Signature: ([J[ILjava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_to_augmented_reality_android_em_recorder_NativeFrameBuffer_read
  (JNIEnv *, jobject, jlongArray, jintArray, jobject);

/*
 * Class:     to_augmented_reality_android_em_recorder_NativeFrameBuffer
 * Method:    readPos
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_to_augmented_reality_android_em_recorder_NativeFrameBuffer_readPos
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
