/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class to_augmented_reality_android_em_recorder_CV */

#ifndef _Included_to_augmented_reality_android_em_recorder_CV
#define _Included_to_augmented_reality_android_em_recorder_CV
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     to_augmented_reality_android_em_recorder_CV
 * Method:    PSNR
 * Signature: (IILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)D
 */
JNIEXPORT jdouble JNICALL Java_to_augmented_reality_android_em_recorder_CV_PSNR
  (JNIEnv *, jclass, jint, jint, jobject, jobject);

/*
 * Class:     to_augmented_reality_android_em_recorder_CV
 * Method:    MSSIM
 * Signature: (IILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)D
 */
JNIEXPORT jdouble JNICALL Java_to_augmented_reality_android_em_recorder_CV_MSSIM
  (JNIEnv *, jclass, jint, jint, jobject, jobject);

/*
 * Class:     to_augmented_reality_android_em_recorder_CV
 * Method:    SHIFT
 * Signature: (IILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[I)V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_recorder_CV_SHIFT
  (JNIEnv *, jclass, jint, jint, jobject, jobject, jintArray);

/*
 * Class:     to_augmented_reality_android_em_recorder_CV
 * Method:    KLUDGE
 * Signature: (IILjava/nio/ByteBuffer;IZLjava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_recorder_CV_KLUDGE
  (JNIEnv *, jclass, jint, jint, jobject, jint, jboolean, jobject);

/*
 * Class:     to_augmented_reality_android_em_recorder_CV
 * Method:    GPUSTATUS
 * Signature: (Ljava/lang/StringBuilder;)Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_recorder_CV_GPUSTATUS
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
