bool YUV2RGBA(const string&, fstream&,  const string&);
char *file_contents(string);
float distance(float bearing1, float bearing2);
bool stats(fstream &, const int, const int, long *, unordered_set<float> *, double &, double &);
void shift(cv::Mat&, int, int,  cv::Mat&, int &, int &);
bool do_shift(const int, const int, Mat&, int, bool, Mat&);
string get_name(string&);
void progress(int, int);
void check_opencl();
bool writeKludgeFile(float, Mat&);
bool readat(fstream &, long, char *);
bool checkRot(fstream&, Mat&, float, double, double, long, int, float&, int&);
