/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu */

#ifndef _Included_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
#define _Included_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
#ifdef __cplusplus
extern "C" {
#endif
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_ARW_MARKER_OPTION_FILTERED
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_ARW_MARKER_OPTION_FILTERED 1L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_ARW_MARKER_OPTION_FILTER_SAMPLE_RATE
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_ARW_MARKER_OPTION_FILTER_SAMPLE_RATE 2L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_ARW_MARKER_OPTION_FILTER_CUTOFF_FREQ
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_ARW_MARKER_OPTION_FILTER_CUTOFF_FREQ 3L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_ARW_MARKER_OPTION_SQUARE_USE_CONT_POSE_ESTIMATION
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_ARW_MARKER_OPTION_SQUARE_USE_CONT_POSE_ESTIMATION 4L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_ARW_MARKER_OPTION_SQUARE_CONFIDENCE
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_ARW_MARKER_OPTION_SQUARE_CONFIDENCE 5L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_ARW_MARKER_OPTION_SQUARE_CONFIDENCE_CUTOFF
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_ARW_MARKER_OPTION_SQUARE_CONFIDENCE_CUTOFF 6L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_LABELING_WHITE_REGION
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_LABELING_WHITE_REGION 0L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_LABELING_BLACK_REGION
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_LABELING_BLACK_REGION 1L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_TEMPLATE_MATCHING_COLOR
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_TEMPLATE_MATCHING_COLOR 0L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_TEMPLATE_MATCHING_MONO
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_TEMPLATE_MATCHING_MONO 1L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_DETECTION
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_DETECTION 2L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_TEMPLATE_MATCHING_COLOR_AND_MATRIX
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_TEMPLATE_MATCHING_COLOR_AND_MATRIX 3L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_TEMPLATE_MATCHING_MONO_AND_MATRIX
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_TEMPLATE_MATCHING_MONO_AND_MATRIX 4L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_3x3
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_3x3 3L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_3x3_PARITY65
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_3x3_PARITY65 259L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_3x3_HAMMING63
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_3x3_HAMMING63 515L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_4x4
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_4x4 4L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_4x4_BCH_13_9_3
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_4x4_BCH_13_9_3 772L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_4x4_BCH_13_5_5
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_4x4_BCH_13_5_5 1028L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_5x5_BCH_22_12_5
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_5x5_BCH_22_12_5 1029L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_5x5_BCH_22_7_7
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_5x5_BCH_22_7_7 1285L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_5x5
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_5x5 5L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_6x6
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_6x6 6L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_GLOBAL_ID
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_MATRIX_CODE_GLOBAL_ID 2830L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_IMAGE_PROC_FRAME_IMAGE
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_IMAGE_PROC_FRAME_IMAGE 0L
#undef to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_IMAGE_PROC_FIELD_IMAGE
#define to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_AR_IMAGE_PROC_FIELD_IMAGE 1L
/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwGetARToolKitVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwGetARToolKitVersion
  (JNIEnv *, jclass);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwInitialiseAR
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwInitialiseAR
  (JNIEnv *, jclass);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwInitialiseARWithOptions
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwInitialiseARWithOptions
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwChangeToResourcesDir
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwChangeToResourcesDir
  (JNIEnv *, jclass, jstring);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwStartRunning
 * Signature: (Ljava/lang/String;Ljava/lang/String;FF)Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwStartRunning
  (JNIEnv *, jclass, jstring, jstring, jfloat, jfloat);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwStartRunningStereo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;FF)Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwStartRunningStereo
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jfloat, jfloat);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwIsRunning
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwIsRunning
  (JNIEnv *, jclass);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwStopRunning
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwStopRunning
  (JNIEnv *, jclass);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwShutdownAR
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwShutdownAR
  (JNIEnv *, jclass);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwGetProjectionMatrix
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwGetProjectionMatrix
  (JNIEnv *, jclass);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwGetProjectionMatrixStereo
 * Signature: ([F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwGetProjectionMatrixStereo
  (JNIEnv *, jclass, jfloatArray, jfloatArray);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwGetVideoParams
 * Signature: ([I[I[I[Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwGetVideoParams
  (JNIEnv *, jclass, jintArray, jintArray, jintArray, jobjectArray);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwGetVideoParamsStereo
 * Signature: ([I[I[I[Ljava/lang/String;[I[I[I[Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwGetVideoParamsStereo
  (JNIEnv *, jclass, jintArray, jintArray, jintArray, jobjectArray, jintArray, jintArray, jintArray, jobjectArray);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwCapture
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwCapture
  (JNIEnv *, jclass);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwUpdateAR
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwUpdateAR
  (JNIEnv *, jclass);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwCaptureUpdate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwCaptureUpdate
  (JNIEnv *, jclass);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwAddMarker
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwAddMarker
  (JNIEnv *, jclass, jstring);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwRemoveMarker
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwRemoveMarker
  (JNIEnv *, jclass, jint);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwRemoveAllMarkers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwRemoveAllMarkers
  (JNIEnv *, jclass);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwQueryMarkerVisibility
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwQueryMarkerVisibility
  (JNIEnv *, jclass, jint);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwQueryMarkerTransformation
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwQueryMarkerTransformation
  (JNIEnv *, jclass, jint);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwQueryMarkerTransformationStereo
 * Signature: (I[F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwQueryMarkerTransformationStereo
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwSetMarkerOptionBool
 * Signature: (IIZ)V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwSetMarkerOptionBool
  (JNIEnv *, jclass, jint, jint, jboolean);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwSetMarkerOptionInt
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwSetMarkerOptionInt
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwSetMarkerOptionFloat
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwSetMarkerOptionFloat
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwGetMarkerOptionBool
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwGetMarkerOptionBool
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwGetMarkerOptionInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwGetMarkerOptionInt
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwGetMarkerOptionFloat
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwGetMarkerOptionFloat
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwSetVideoDebugMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwSetVideoDebugMode
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwGetVideoDebugMode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwGetVideoDebugMode
  (JNIEnv *, jclass);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwSetVideoThreshold
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwSetVideoThreshold
  (JNIEnv *, jclass, jint);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwGetVideoThreshold
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwGetVideoThreshold
  (JNIEnv *, jclass);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwSetVideoThresholdMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwSetVideoThresholdMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwGetVideoThresholdMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwGetVideoThresholdMode
  (JNIEnv *, jclass);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwAcceptVideoImage
 * Signature: ([BIIIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwAcceptVideoImage
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jboolean);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwAcceptVideoImageStereo
 * Signature: ([BIIIZ[BIIIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwAcceptVideoImageStereo
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jboolean, jbyteArray, jint, jint, jint, jboolean);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwUpdateDebugTexture32
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwUpdateDebugTexture32
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwSetLabelingMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwSetLabelingMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwGetLabelingMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwGetLabelingMode
  (JNIEnv *, jclass);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwSetPatternDetectionMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwSetPatternDetectionMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwGetPatternDetectionMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwGetPatternDetectionMode
  (JNIEnv *, jclass);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwSetBorderSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwSetBorderSize
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwGetBorderSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwGetBorderSize
  (JNIEnv *, jclass);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwSetMatrixCodeType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwSetMatrixCodeType
  (JNIEnv *, jclass, jint);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwGetMatrixCodeType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwGetMatrixCodeType
  (JNIEnv *, jclass);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwSetImageProcMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwSetImageProcMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu
 * Method:    arwGetImageProcMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_to_augmented_reality_android_em_artoolkitem_NativeInterfaceEmu_arwGetImageProcMode
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
