/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class to_augmented_reality_android_em_recorder_RGBAtoRGB_StripeConvertor */

#ifndef _Included_to_augmented_reality_android_em_recorder_RGBAtoRGB_StripeConvertor
#define _Included_to_augmented_reality_android_em_recorder_RGBAtoRGB_StripeConvertor
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
