/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class to_augmented_reality_android_em_recorder_RGBAtoRGB */

#ifndef _Included_to_augmented_reality_android_em_recorder_RGBAtoRGB
#define _Included_to_augmented_reality_android_em_recorder_RGBAtoRGB
#ifdef __cplusplus
extern "C" {
#endif
#undef to_augmented_reality_android_em_recorder_RGBAtoRGB_RGBA_STRIDE
#define to_augmented_reality_android_em_recorder_RGBAtoRGB_RGBA_STRIDE 4L
#undef to_augmented_reality_android_em_recorder_RGBAtoRGB_RGB_STRIDE
#define to_augmented_reality_android_em_recorder_RGBAtoRGB_RGB_STRIDE 3L
/*
 * Class:     to_augmented_reality_android_em_recorder_RGBAtoRGB
 * Method:    nativeRGBAtoRGB
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_recorder_RGBAtoRGB_nativeRGBAtoRGB
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     to_augmented_reality_android_em_recorder_RGBAtoRGB
 * Method:    nativeRGBAtoRGB565
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_to_augmented_reality_android_em_recorder_RGBAtoRGB_nativeRGBAtoRGB565
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
